### ISSUE TITLE
How to make S/N ratio plots as shown on readthedocs?

### ISSUE THREAD

**Issue by wholden** [kklmn/XAFSmass#1]
Hello, I installed your tool and found it very user friendly.  I had a question about something from the readthedocs, and I wasn't sure where to ask about it, so I'm using GitHub issues, I hope that's alright.

Looking at the https://xafsmass.readthedocs.io/ page, I found your S/N ratio plots quite interesting.  I looked through the source code but didn't notice any way of making those plots or doing those kind of calculations.  Is it possible to do those using the package, or would you be able to upload an example of those calculations?

I'm interested in particular because I'm working with XAFS using a laboratory instrument instead of a synchrotron beamline, so instead of having an upstream and downstream ionization detector, we measure I_zero with no sample, and I_t with the sample in front of the detector, so I'm curious how that effects the optimal S/N and therefore the optimal mu_t*d.

**Comment by kklmn** [comment]
Hi,
The plots are based on [P. A. Lee, P. H. Citrin, P. Eisenberger, and B. M. Kincaid, Rev. Mod. Phys. 53, 769](https://journals.aps.org/rmp/abstract/10.1103/RevModPhys.53.769), sec II.B.1.a, Eq(2.13). If fluctuations of I0 are ignored, the formula is yet simplified; the maximum is at µTd=2:
<img src="https://user-images.githubusercontent.com/17322580/51711274-e2aa3980-202b-11e9-8245-0fb7aa506736.png" width="400">
This script makes the plots
[plotsSN.zip](https://github.com/kklmn/XAFSmass/files/2793847/plotsSN.zip)

**Comment by wholden** [comment]
That's great, thanks so much for the quick reply and for the citation!
